### ISSUE TITLE
Add commit information (including author and dates) for the website pages

### ISSUE THREAD

**Issue by jonaprieto** [UniMath/agda-unimath#439]
We might need to run a script or write our mdbook preprocessor to add this information to each webpage. See https://rust-lang.github.io/mdBook/for_developers/preprocessors.html#hints-for-implementing-a-preprocessor.

**Comment by jonaprieto** [comment]
A starting point could be: https://gist.githubusercontent.com/jonaprieto/4fc4a98e147ef60c15f5ae6b03b04205/raw/6e3149fc37c7d53fc02911dcd25b3bcea04845bb/update-page-git.py

**Comment by EgbertRijke** [comment]
I think your proposal is reasonable.

One thing that is not so clear to me though, is that if person 2 moves a portion of code written by person 1 to a different file, then git doesn't track that the moved piece of code was originally due to person 1. It will just track person 1's authorship on the original file, which doesn't contain the moved piece of code anymore, and person 2 will now get authorship in the file they moved person 1's code to. So there needs to be some kind of disclaimer, because code actually gets moved around in our library.

**Comment by VojtechStep** [comment]
That is true, git isn't really sophisticated enough to keep track of that information. I will need some input for the specific arrangement on the website (I have zero aesthetic sense), so let me open a PR with the technical implementation tonight and then we can discuss the wording there as well.

**Comment by EgbertRijke** [comment]
Instead of speaking of authors we could speak of contributors. Either way, when people submit work to agda-unimath it is with the understanding that the material may be freely copied and altered by anyone for any purpose, because we're under an MIT licence.

**Comment by EgbertRijke** [comment]
I'd be fine with it if in the initial version we have this information at the bottom of each page. But it would also be reasonable to display the contributors directly under the title of the page, and the recent git commit information at the bottom of the page.

**Comment by EgbertRijke** [comment]
Could there be a way that the list of contributors to a page is added by a script similar to how we generate the indexing files, but in such a way that we can manually add contributors if we feel there is a need for it, and the script makes sure the contributors are listed in alphabetic ordering.

It could also be fun to add a page for each contributor to the website, where we could display some basic information such as links to homepages and github profiles, as well as list all the files in agda-unimath they have contributed to. I think that wouldn't be too hard to maintain, because most of it would be automatically generated.

**Comment by VojtechStep** [comment]
> Could there be a way that the list of contributors to a page is added by a script similar to how we generate the indexing files, but in such a way that we can manually add contributors if we feel there is a need for it, and the script makes sure the contributors are listed in alphabetic ordering.

That should technically be possible, but it would require better specification of what we want; for now I'd say we can leave it at whatever information we get from git, and if we feel the need to intervene, we can open a new issue for that. What do you think?

> It could also be fun to add a page for each contributor to the website, where we could display some basic information such as links to homepages and github profiles, as well as list all the files in agda-unimath they have contributed to. I think that wouldn't be too hard to maintain, because most of it would be automatically generated.

Definitely, we already have an autogenerated CONTRIBUTORS page (although running the script isn't automated), and that should be extendable.

**Comment by VojtechStep** [comment]
Oh, but I also think that the personalized Contributors page should have its own issue. Would you like to open one?
