### ISSUE TITLE
Add precedence and fixity to (standard) binary operators

### ISSUE THREAD

**Issue by fredrik-bakke** [UniMath/agda-unimath#479]
I figured we could compile a list of operators and propose fixities and constraints on what should precede what if we indeed want to define this in the library.

Some of my initial suggestions are as follows.

#### Fixity
- Function composition should associate to the right.
`f ∘ g ∘ h` means `f ∘ (g ∘ h)`.
- ~Identification concatenation should associate to the left as concatenation is done in diagrammatic order.
`p ∙ q ∙ r` means `(p ∙ q) ∙ r`.~
- ~Homotopy concatenation should associate to the left as concatenation is done in diagrammatic order.
`p ∙h q ∙h r` means `(p ∙h q) ∙h r`.~
- Homotopy left whiskering should associate to the right.
`f ·l g ·l H` only makes sense as `f ·l (g ·l H)`.
Although in this instance it would also make sense to just write `(f ∘ g) ·l H`.
- Homotopy right whiskering should associate to the left.
`H ·r g ·r f` only makes sense as `(H ·r g) ·r f`.
- Products and coproducts should associate to the right.
`A × B × C` means `A × (B × C)`, and `A + B + C` means `A + (B + C)`.
- Identity and homotopy type formation should not associate to either side.
`x ＝ y ＝ z` is ambiguous, `f ~ g ~ h` is always ill-typed.

#### Precedence
- Function composition, homotopy concatenation, homotopy left whiskering, and homotopy right whiskering should have precedence over identity and homotopy type formation.
E.g. `f ∘ g ~ h` means `(f ∘ g) ~ h`.
- Identification concatenation should have precedence over identity type formation.
`p ∙ q ＝ r` means `(p ∙ q) ＝ r`.
- Identification concatenation, homotopy concatenation, homotopy left whiskering, and homotopy right whiskering should have the same precedence.
- Function composition should have the same precedence level as homotopy concatenation, and homotopy right whiskering.
e.g. `H ∙h K ∘ f` and `H ·r g ∘ f` are ambiguous (note that this is not an issue with left whiskering).
- Homotopy type formation could have precedence over identity type formation,
as `f ~ g ＝ X` only ever makes sense as `(f ~ g) ＝ X` since functions cannot be homotopic to types.
- Products should have precedence over, or the same precedence, as coproducts.
e.g. `A × B + C` means `(A × B) + C` or is ambiguous.
- The operator `_∘_` may have precedence over `_,_`, as the alternative is always ill-typed.
e.g. `f , g ∘ h` means `f , (g ∘ h)`.

**Comment by EgbertRijke** [comment]
I quite like to put parentheses. It displays the structure of what is written more clearly. That's why I never bothered with fixing which way operators associate or their precedence levels. On the other hand, I'm not opposed to this proposal.

I see two clearly separate cases groups of proposals in the Fixity section: Those operators for which associating it one way or another is definitionally determined, and those which aren't. 

For function composition, it doesn't matter which way we associate, because both ways of writing the parentheses are judgmentally equal. 

For whiskering, the proposal is good, because the other way is ill-typed. So there is only one possible convention we can take.

For concatenation of identifications and identifications, however, I think it is better not to pick an arbitrary direction in which to associate. It is better to write the parentheses in those cases, because when you have to reason about concatenated paths it is useful if the structure of the concatenation is clearly visible in the code. 

I think also the choice for associating coproducts and products feels quite arbitrary, and therefore I would be reluctant to make a choice. 

Having said this, I'm still not entirely opposed to this proposal. When we go for this, we should have a page PRECEDENCE-LEVELS that clearly explains our choices.

**Comment by fredrik-bakke** [comment]
Thank you for the input. I think you bring up a very good point about definitional determination. Moreover, a good rule of thumb that should be mentioned is that the precedence and fixity rules should be intuitive and "obvious." Otherwise, it is contra-productive to omit the parentheses.

With this in mind, I think the fixity rules for function composition and the homotopy whiskering operations, as well as the precedence rule that function composition, identification concatenation, homotopy concatenation, and homotopy whiskering operations should precede identity and homotopy type formation, would still be improvements to the library.

**Comment by fredrik-bakke** [comment]
Also, one more remark. I think the information on precedence levels and fixities fit naturally together with an explanation of special notation that is used in general. Maybe this fits in `CODINGSTYLE.md`?

**Comment by fredrik-bakke** [comment]
While on the topic, I would like to propose that we rename the wedge of pointed types from `_∨_` to `_∨*_`, leaving the former open for use as the propositional disjunction. Similarly, I'd propose using `_∧*_` for the smash product, leaving `_∧_` open for propositional conjunction.

**Comment by fredrik-bakke** [comment]
Another question! Should there be binary operator notation for various multiplication operations, e.g. multiplication on natural numbers? If so, which symbol should be used?

```md
x×*⋆∙·
```
I.e.
- `_xℕ_`
- `_xℕ_`
- `_xℕ_`
- `_xℕ_`

**Comment by fredrik-bakke** [comment]
Here's another heuristic we may use:
Infix operators that don't take values in types should take precedence over operators that do, as the alternative interpretation will in most cases be ill-typed.
E.g.
```agda
x +ℕ y ＝ z
```
can only be interpreted as
```agda
(x +ℕ y) ＝ z
```

The notable counter-example would of course be a binary operator that takes types as inputs and spits out something which isn't. E.g.
```agda
_weird_ : UU → UU → ℕ
X weird Y = zero-ℕ
```
