### ISSUE TITLE
Equivalent definition of countability

### ISSUE THREAD

**Issue by ElifUskuplu** [UniMath/agda-unimath#567]
I'm working on the equivalent definitions of countable types. I've proved `is-countable` implies `is-countable'`. For the other direction, there was an unfinished work in the previous version
```
module _
  {l : Level} (X : UU-Set l)
  where
{-
  is-countable-is-countable' :
    is-countable' X → is-countable X
  is-countable-is-countable' H =
    apply-universal-property-trunc-Prop H
      ( is-countable-Prop X)
      ( λ (P , f) →
        unit-trunc-Prop
          ( pair
            ( λ n →
              map-coprod
                ( λ { (zero-ℕ , p) → ex-falso p ;
                      (succ-ℕ n , p) → map-surjection f (n , p)})
                ( λ x → star)
                ( map-left-distributive-Σ-coprod ℕ
                  ( {!is-in-decidable-subtype ∘ ?!})
                  ( ¬ ∘ shift-ℕ empty (is-in-decidable-subtype P))
                  ( pair n
                    ( is-decidable-subtype-decidable-subtype
                      ( shift-ℕ empty-decidable-Prop P) {!!}))))
            {!!}))
            -}
```
```
-- ℕ → Σ (n : ℕ), P' n + ¬ (P' n)
--   → (Σ (n : ℕ), P' n) + (Σ (n : ℕ), ¬ (P' n))
--   → X + 1

-- P' := shift-ℕ ∅ P
````
I couldn't understand how we define `ℕ → Σ (n : ℕ), P' n + ¬ (P' n)`. Do you have any suggestion/idea?

**Comment by EgbertRijke** [comment]
The idea is that if there is a surjective map `f : ℕ → Maybe X`, then we obtain a decidable subtype `P` of `ℕ` by testing whether `f n` is a value or an exception, which is decidable.

**Comment by ElifUskuplu** [comment]
Yes, but what you said is about that `is-countable` implies `is-countable'`, I've already used that approach to prove this. My concern was about the other direction.

**Comment by EgbertRijke** [comment]
If there is a decidable subtype `P` of `ℕ` that surjects onto `X`, then define `Q` to be `Q n := P (n + 1)` so that `0` is not in `Q`. Then `Q` surjects onto `X`, and by decidability it follows that `ℕ` surjects onto `Maybe X`.

**Comment by EgbertRijke** [comment]
I made a mistake when typing up the idea: I intended `Q 0 := empty` and `Q (n + 1) := P n`.

**Comment by ElifUskuplu** [comment]
Got it, thanks.

**Comment by ElifUskuplu** [comment]
I understand the idea. But when I'm applying, there is a problem I couldn't solve.
```agda
 shift-decidable-subtype-ℕ :
    decidable-subtype l ℕ → decidable-subtype l ℕ
  shift-decidable-subtype-ℕ P zero-ℕ =
    ( raise-empty l) ,
    ( is-prop-raise-empty ,
      ( inr (map-inv-equiv (compute-raise-empty l))))
  shift-decidable-subtype-ℕ P (succ-ℕ n) = P n

  decidable-subtype-ℕ-to-Maybe :
    ( P : decidable-subtype l ℕ) → 
    ( type-decidable-subtype P → type-Set X) →
    ( (type-decidable-subtype (shift-decidable-subtype-ℕ P)) →
      ( Maybe (type-Set X)))
  decidable-subtype-ℕ-to-Maybe P f (zero-ℕ , p) = inr star
  decidable-subtype-ℕ-to-Maybe P f (succ-ℕ n , p) = inl (f (n , p))

  is-surjective-decidable-subtype-ℕ-to-Maybe :
    ( P : decidable-subtype l ℕ) → 
    ( (f , H) : type-decidable-subtype P ↠ type-Set X) →
    ( is-surjective (decidable-subtype-ℕ-to-Maybe P f))
  is-surjective-decidable-subtype-ℕ-to-Maybe P (f , H) (inl x) =
    ( apply-universal-property-trunc-Prop (H x)
      ( trunc-Prop (fib _ (inl x)))
      ( λ y → unit-trunc-Prop ((succ-ℕ (pr1 (pr1 y)) , pr2 (pr1 y)) , ap inl (pr2 y))))
  is-surjective-decidable-subtype-ℕ-to-Maybe P (f , H) (inr star) =
    unit-trunc-Prop ((0 , {!!}) , refl)
```
At the end, I need a produce a term in `empty` which is not possible. What am I missing?

**Comment by EgbertRijke** [comment]
In the definition `shift-decidable-subtype-ℕ` you could use `is-empty-raise-empty` instead of `map-inv-equiv (compute-raise-empty l)`. The former is more clear.

To prove that there is a surjective map `ℕ → Maybe X` you have to change the definition of `decidable-subtype-ℕ-to-Maybe` that it produces a map `ℕ → Maybe X`. Currently it produces just a map from `type-decidable-subtype shift-decidable-subtype-ℕ` into `Maybe X`. Once you fixed the definition, you'll probably get through the proof of surjectivity alright. Let me know if you have further trouble.

**Comment by ElifUskuplu** [comment]
I've tried this, too:
```agda

  decidable-subtype-ℕ-to-Maybe :
    ( P : decidable-subtype l ℕ) → 
    ( type-decidable-subtype P → type-Set X) →
    ( ℕ → Maybe (type-Set X))
  decidable-subtype-ℕ-to-Maybe P f zero-ℕ = inr star
  decidable-subtype-ℕ-to-Maybe P f (succ-ℕ n) = inl {!!}
```
The problem is that for any `n`, I need a term in `pr1 (P n)` , but this is not taken for granted, right? Also, since this does not refer `shift-decidable-subtype-ℕ`, it seems wrong.

**Comment by EgbertRijke** [comment]
One more comment: we don't use the naming scheme `X-to-Y` in the library. Perhaps we could come up with a better naming scheme as follows:

1. Define `enumeration X` to be the type of surjective maps `ℕ → Maybe X`. Then we can define `map-enumeration` for the underlying map and `is-surjective-enumeration` for the proof that it is surjective. This will now set up the first part of a nice naming scheme.
2. Perhaps we should call `decidable-subprojection-ℕ` the type of surjections out of a decidable subtype of `ℕ`. This data gives a set `X` the structure of a quotient of a decidable subset of `ℕ`. But it wouldn't make much sense to call them decidable subquotients, because that would be the type of all such `X` equipped with a surjection out of a decidable subtype of `ℕ`. Perhaps there is a better name, but decidable subprojection seems reasonable for the structure of a decidable subtype of `ℕ` equipped with a surjective map from its underlying type into `X`. Once we fix the name, we can define `decidable-subtype-decidable-subprojection-ℕ`, `subtype-decidable-subprojection-ℕ`, ... (and infrastructure similar to that of decidable subtypes), and `surjection-decidable-subprojection-ℕ`, `map-surjection-decidable-subprojection-ℕ`, and `is-surjective-surjection-decidable-subprojection-ℕ`. Setting up so much names may seem like a lot of work, but once you have it it will help writing your agda proofs clearly and furthermore it will be obvious what to call things because you're setting up a clear naming scheme.
3. If you like my suggestion in 2. above, then we can call your map `decidable-subtype-ℕ-to-Maybe` by a new name following the agda-unimath naming scheme: `map-enumeration-decidable-subprojection-ℕ` for the underlying map, and the proof that it is surjective can be called `is-surjective-enumeration-decidable-subprojection-ℕ`. These two can then be combined to form the element `enumeration-decidable-subprojection-ℕ` which takes a decidable subprojection of `ℕ` as an argument and produces an enumeration of `X`.

**Comment by EgbertRijke** [comment]
> I've tried this, too:
> 
> ```agda
>   decidable-subtype-ℕ-to-Maybe :
>     ( P : decidable-subtype l ℕ) → 
>     ( type-decidable-subtype P → type-Set X) →
>     ( ℕ → Maybe (type-Set X))
>   decidable-subtype-ℕ-to-Maybe P f zero-ℕ = inr star
>   decidable-subtype-ℕ-to-Maybe P f (succ-ℕ n) =  inl (f (n , {!!}))
> ```
> 
> The problem is that for any `n`, I need a term in `pr1 (P n)` , but this is not taken for granted, right? Also, since this does not refer `shift-decidable-subtype-ℕ`, it seems wrong.

You need to use that `shift-decidable-subtype-ℕ` is decidable

**Comment by EgbertRijke** [comment]
To use that `shift-decidable-subtype-ℕ` is decidable you have two options:

1. Use `with`-abstraction. We're not completely against `with`-abstraction in this library, but agda's functionality for `with`-abstraction is very limited. Especially proving things about functions defined with `with`-abstraction can be complicated for obscure reasons that come down to agda's limited support for `with`-abstraction.
2. Write a helper function by hand. In this case you would write a function

```agda
  cases-decidable-subtype-ℕ-to-Maybe :
    ( P : decidable-subtype l ℕ) → 
    ( type-decidable-subtype P → type-Set X) →
    ( (n : ℕ) → is-decidable (P n) -> Maybe (type-Set X))
  ```

This can be done with a simple case analysis. And then you write the function `decidable-subtype-ℕ-to-Maybe` by calling `cases-decidable-subtype-ℕ-to-Maybe` and the proof that `P` is a decidable subtype of `ℕ`.

This proof strategy is explained in more detail in section 8.2 (or 8.3, I forgot) of my book.

**Comment by ElifUskuplu** [comment]
I'll edit the names before submitting a PR. Thanks for the advice.

I understand what you mean, I'm working on the last suggestion now.

But let me check one thing: `shift-decidable-subtype-ℕ P n` is actually a triple 
```agda
(Aₙ, pₙ, dₙ) : Σ (UU l) (λ A  → is-prop (A) x is-decidable (A))
```
And `type-decidable-subtype (shift-decidable-subtype-ℕ P)` consists of pairs `(n,Aₙ)`. Are these correct?

**Comment by EgbertRijke** [comment]
Yes, that's correct except that `type-decidable-subtype (shift-decidable-subtype-ℕ P)` consists of pairs `(n,aₙ)` where `aₙ : Aₙ`.

**Comment by ElifUskuplu** [comment]
I solved, and I understand my mistake. Actually, I know the strategy here and used in many times

> This proof strategy is explained in more detail in section 8.2 (or 8.3, I forgot) of my book.

But, here, we need a extra map before applying this. (ignore names for now :))
```agda

  shift-decidable-subtype-ℕ :
    decidable-subtype l ℕ → decidable-subtype l ℕ
  shift-decidable-subtype-ℕ P zero-ℕ =
    ( raise-empty l) ,
    ( is-prop-raise-empty ,
      ( inr (is-empty-raise-empty)))
  shift-decidable-subtype-ℕ P (succ-ℕ n) = P n

  FFF : 
    ( P : decidable-subtype l ℕ) → 
    ( type-decidable-subtype P → type-Set X) →
    (n : ℕ) → (is-decidable (pr1 (P n)) -> Maybe (type-Set X))
  FFF P f n (inl x) = inl (f (n , x))
  FFF P f n (inr x) = inr star

  QQQ : 
    ( P : decidable-subtype l ℕ) → 
    ( type-decidable-subtype P → type-Set X) →
    ( type-decidable-subtype (shift-decidable-subtype-ℕ P) → type-Set X)
  QQQ P f (zero-ℕ , map-raise ())
  QQQ P f (succ-ℕ n , p) = f  (n , p)


  decidable-subtype-ℕ-to-Maybe :
    ( P : decidable-subtype l ℕ) → 
    ( type-decidable-subtype P → type-Set X) →
    ( ℕ → Maybe (type-Set X))
   decidable-subtype-ℕ-to-Maybe P f n = 
         FFF (shift-decidable-subtype-ℕ P) (QQQ P f) n (pr2 (pr2 ((shift-decidable-subtype-ℕ P) n)))
```
Then, it's easy to handle surjectivity.

**Comment by EgbertRijke** [comment]
Excellent!

**Comment by ElifUskuplu** [comment]
Thanks for your help.

**Comment by EgbertRijke** [comment]
Thank you for doing this Elif!
