### ISSUE TITLE
pre-commit shouldn't give an error on empty sections

### ISSUE THREAD

**Issue by EgbertRijke** [UniMath/agda-unimath#721]
I think I don't really like that we get an error on empty sections. It should perhaps just be a warning. With the error, it is impossible to lay out the file structure unless you write something like "to do" under each section header, but that is ugly.

**Comment by fredrik-bakke** [comment]
It's not impossible in the sense that you cannot do it and push empty sections to your local branch, but pre-commit will block it from being merged into the master branch, which was the reason why it was introduced. I don't think empty sections belong in the master branch. There, I think the fact that a section is empty should at least be addressed by writing something like "This remains to be formalized.", to make the intention clear. This also opens up for the possibility to elaborate more on how one would proceed, since there is a reasonable chance the original contributor will not finish the section. Do you disagree with this?

**Comment by fredrik-bakke** [comment]
Have we come to an agreement on this issue?
