### ISSUE TITLE
Discuss replacing `-whisk-` with `-whisker-`

### ISSUE THREAD

**Issue by VojtechStep** [UniMath/agda-unimath#982]
I think "whisk" vs "whisker" is not enough of a character count improvement to impede on readability, but that can be addressed in another PR.

_Originally posted by @EgbertRijke in https://github.com/UniMath/agda-unimath/pull/972#discussion_r1421037483_

**Comment by fredrik-bakke** [comment]
While I'm not very fond of `whisk`, we had a discussion in the past about `comp` vs. `compose` and settled on `comp`. This was because we don't generally like imperative forms of verbs. Thus `whisker` should not be understood/used as an imperative. We could also consider using `whiskering`, like we do `pasting` as opposed to `paste`.

**Comment by fredrik-bakke** [comment]
This is resolved by #1014.
